// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Running Test Program:");

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: {
        hd: 4,
        tl: /* [] */0
      }
    }
  }
};

console.log(myList);

exports.myList = myList;
/*  Not a pure module */
