// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

console.log("Hello World");

var myVar = "Hello World";

console.log(myVar);

var alex = {
  name: "Alex Merced",
  age: 34
};

console.log(alex);

var superman = {
  TAG: /* Hero */0,
  _0: "Superman"
};

var result;

result = typeof superman === "number" ? "I am just me" : (
    superman.TAG ? "I am Superman and I'm here to ruin the day" : "I am Superman and I'm here to save the day"
  );

console.log(result);

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: {
        hd: 4,
        tl: {
          hd: 5,
          tl: /* [] */0
        }
      }
    }
  }
};

console.log(myList);

var nextList = {
  hd: 0,
  tl: myList
};

console.log(nextList);

var myArray = [
  1,
  2,
  3
];

console.log(myArray);

console.log(Caml_array.caml_array_get(myArray, 2));

function myFunc(x, y, z) {
  return (x + y | 0) + z | 0;
}

function one(param, param$1) {
  return myFunc(1, param, param$1);
}

function two(param) {
  return myFunc(1, 2, param);
}

var three = 6;

console.log(three);

function thisFunc(first, last) {
  return first + (" " + last);
}

console.log("Alex Merced");

console.log(6);

function addOne(x) {
  return x + 1 | 0;
}

console.log(8);

var myIf = 6;

var myResult = 8;

exports.myVar = myVar;
exports.alex = alex;
exports.superman = superman;
exports.result = result;
exports.myList = myList;
exports.nextList = nextList;
exports.myArray = myArray;
exports.myFunc = myFunc;
exports.one = one;
exports.two = two;
exports.three = three;
exports.thisFunc = thisFunc;
exports.myIf = myIf;
exports.addOne = addOne;
exports.myResult = myResult;
/*  Not a pure module */
