// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var myMap = {};

myMap["Name"] = "Alex Merced";

console.log(myMap);

var alex = {
  name: "Alex Merced",
  age: 34
};

console.log(alex);

function addOne(x) {
  return x + 1 | 0;
}

console.log(6);

function addThree(x, y, z) {
  return (x + y | 0) + z | 0;
}

function one(param, param$1) {
  return addThree(1, param, param$1);
}

function two(param) {
  return addThree(1, 2, param);
}

var three = 6;

console.log(three);

var result = 6;

exports.myMap = myMap;
exports.alex = alex;
exports.addOne = addOne;
exports.result = result;
exports.addThree = addThree;
exports.one = one;
exports.two = two;
exports.three = three;
/*  Not a pure module */
